### ISSUE TITLE
Pagiante and ordering seems to be conflicting

### ISSUE THREAD

**Issue by tadeoos** [plecto/django-smart-lists#20]
When I declare `ordering` and `paginate_by` on a view I get `AssertionError`

`AssertionError: Cannot reorder a query once a slice has been taken.`

Issue is with line 280 in `helpers.py`
```python
elif issubclass(type(self.model_field), ForeignKey):
    pks = self.object_list.order_by().distinct().values_list('%s__pk' % self.field_name, flat=True)
```

**Comment by pax0r** [comment]
The exact problem is not with "ordering" but with the way how smart-lists handle getting values for filters based on ForeignKey.
